import Desktop from "../assets/images/Desktop.jpg";
import Laptop from "../assets/images/Laptop.png";
import Samsung from "../assets/images/Samsung.jpg";
import Ipad from "../assets/images/Ipad.jpg";
import Iphone from "../assets/images/Iphone.png";

const data = [
  {
    id: 1,
    title: "Hp Laptop",
    price: 55000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Laptop, Desktop, Samsung, Ipad, Iphone],
    // img:  Laptop,
  },
  {
    id: 2,
    title: "Samsung Phone",
    price: 70000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Samsung, Desktop, Laptop, Ipad, Iphone],
    // img: Samsung,
  },
  {
    id: 3,
    title: "Ipad Pro",
    price: 60000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Ipad, Desktop, Samsung, Laptop, Iphone],
    // img: Ipad,
  },
  {
    id: 4,
    title: "Desktop Computer",
    price: 80000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Desktop, Laptop, Samsung, Ipad, Iphone],
    // img: Desktop,
  },
  {
    id: 5,
    title: "Iphone 13 pro",
    price: 120000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Iphone, Desktop, Samsung, Ipad, Laptop],
    // img: Iphone,
  },
  {
    id: 6,
    title: "Hp Laptop",
    price: 55000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Laptop, Desktop, Samsung, Ipad, Iphone],
    // img: Laptop,
  },
  {
    id: 7,
    title: "Samsung Phone",
    price: 70000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Samsung, Desktop, Laptop, Ipad, Iphone],
    // img: Samsung,
  },
  {
    id: 8,
    title: "Ipad Pro",
    price: 60000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Ipad, Desktop, Samsung, Laptop, Iphone],
    // img: Ipad,
  },
  {
    id: 9,
    title: "Desktop Computer",
    price: 80000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Desktop, Laptop, Samsung, Ipad, Iphone],
    // img: Desktop,
  },
  {
    id: 10,
    title: "Iphone 13 pro",
    price: 120000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Iphone, Desktop, Samsung, Ipad, Laptop],
    // img: Iphone,
  },
  {
    id: 11,
    title: "Hp Laptop",
    price: 55000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Laptop, Desktop, Samsung, Ipad, Iphone],
    // img: Laptop,
  },
  {
    id: 22,
    title: "Samsung Phone",
    price: 70000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Samsung, Desktop, Laptop, Ipad, Iphone],
    // img: Samsung,
  },
  {
    id: 13,
    title: "Ipad Pro",
    price: 60000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Ipad, Desktop, Samsung, Laptop, Iphone],
    // img: Ipad,
  },
  {
    id: 14,
    title: "Desktop Computer",
    price: 80000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Desktop, Laptop, Samsung, Ipad, Iphone],
    // img: Desktop,
  },
  {
    id: 15,
    title: "Iphone 13 pro",
    price: 120000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Iphone, Desktop, Samsung, Ipad, Laptop],
    // img: Iphone,
  },
  {
    id: 16,
    title: "Hp Laptop",
    price: 55000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Laptop, Desktop, Samsung, Ipad, Iphone],
    // img: Laptop,
  },
  {
    id: 17,
    title: "Samsung Phone",
    price: 70000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Samsung, Desktop, Laptop, Ipad, Iphone],
    // img: Samsung,
  },
  {
    id: 18,
    title: "Ipad Pro",
    price: 60000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Ipad, Desktop, Samsung, Laptop, Iphone],
    // img: Ipad,
  },
  {
    id: 19,
    title: "Desktop Computer",
    price: 80000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Desktop, Laptop, Samsung, Ipad, Iphone],
    // img: Desktop,
  },
  {
    id: 20,
    title: "Iphone 13 pro",
    price: 120000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Iphone, Desktop, Samsung, Ipad, Laptop],
    // img: Iphone,
  },
  {
    id: 21,
    title: "Hp Laptop",
    price: 55000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Laptop, Desktop, Samsung, Ipad, Iphone],
    // img: Laptop,
  },
  {
    id: 22,
    title: "Samsung Phone",
    price: 70000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Samsung, Desktop, Laptop, Ipad, Iphone],
    // img: Samsung,
  },
  {
    id: 23,
    title: "Ipad Pro",
    price: 60000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Ipad, Desktop, Samsung, Laptop, Iphone],
    // img: Ipad,
  },
  {
    id: 24,
    title: "Desktop Computer",
    price: 80000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Desktop, Laptop, Samsung, Ipad, Iphone],
    // img: Desktop,
  },
  {
    id: 25,
    title: "Iphone 13 pro",
    price: 120000,
    discount: 10,
    quantity: 1,
    des: " There are many variations of items.",
    img: [Iphone, Desktop, Samsung, Ipad, Laptop],
    // img: Iphone,
  },
];

export default data;
